### ISSUE TITLE
Add custom domains to Heroku

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#107]
* [x] stage.ksvotes.org pointing at staging app
* [x] SSL cert for stage.ksvotes.org
* [x] v2.ksvotes.org pointing at production app
* [x] SSL cert for v2.ksvotes.org

https://devcenter.heroku.com/articles/custom-domains

**Comment by karpet** [comment]
This requires "manage" permission at Heroku.

**Comment by jakelowen** [comment]
See screenshots. Will this suffice? Might take a moment for SSL cert to resolve.

![image](https://user-images.githubusercontent.com/5368008/42651530-43563776-85d5-11e8-94f9-c7d37ad53fcb.png)

![image](https://user-images.githubusercontent.com/5368008/42651580-6a561940-85d5-11e8-9e73-3b3e60463488.png)

**Comment by karpet** [comment]
Looks great thanks @jakelowen

**Comment by jakelowen** [comment]
It appears certs are resolving now.
