### ISSUE TITLE
Retain address from VoterView?

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#121]
When I put in my county/birthdate and it pulls back my address, can that address be kept and inserted into the AB app flow?

**Comment by karpet** [comment]
good question. I had been thinking about how to parse the raw HTML that VoterView returns. It would be a little tricky given the way it is returned, but we could auto-populate and let voters correct it.

**Comment by karpet** [comment]
This is now possible as of 39c8c0e but still needs to be implemented. Seems like a nice-to-have so giving it a medium priority.

**Comment by katherinepdavis** [comment]
Not sure if this belongs in the same issue, but it could also pull party for primary AB requests.
