### ISSUE TITLE
Format county clerk info

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#125]
Just so it's a little prettier. Dashes in the phone #s, that kind of thing. I assume this can be done in the csv itself? With that I'll assign myself.

**Comment by karpet** [comment]
we can also fix the presentation via code. Not hard to format phone numbers. Let me know if you want it automated.

**Comment by katherinepdavis** [comment]
@karpet Is this done or do I need to do something?

**Comment by katherinepdavis** [comment]
Let's put dashes in phone numbers. Low priority.
