### ISSUE TITLE
Social cards

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#13]
For sharing on Facebook/Twitter

* [x] default image asset
* [x] default description text
* [ ] any custom per-URL overrides?

**Comment by karpet** [comment]
Open Graph tags should be implemented once for the site layout template.

**Comment by karpet** [comment]
Open Graph tags are in the template. Just need content: image and description.

**Comment by karpet** [comment]
@katherinepdavis assigning this to you, to make sure you are aware we need you to identify image and description for social cards.

**Comment by katherinepdavis** [comment]
![ksvotes_logo_alternative_cmyk](https://user-images.githubusercontent.com/30677505/41871253-00c30b72-7884-11e8-96a5-e0dab8b16e15.png)
KSVotes.org is the fastest, simplest way to register to vote in Kansas using just your touchscreen device.

**Comment by karpet** [comment]
![screen shot 2018-08-02 at 11 57 56 pm](https://user-images.githubusercontent.com/99722/43624962-f79a865c-96af-11e8-95c1-430283ce2979.png)

**Comment by katherinepdavis** [comment]
It's fine for me now.

Is the warning (The following required properties are missing: fb:app_id) something to be concerned with?
