### ISSUE TITLE
Needs explainer on VR 7

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#130]

**Comment by katherinepdavis** [comment]
And move county clerk info to top?

**Comment by katherinepdavis** [comment]
They should be able to choose a different county clerk if our lookup is incorrect.

**Comment by karpet** [comment]
The clerk info comes from the county they have selected earlier. Are you saying they should be able to switch county selection on Step 7?

Clerk info is now displayed at the top in master.

**Comment by karpet** [comment]
* [ ] add county selector to Step 7 (both flows). change "Submit" button on select to "Update County", insert additional "Update County" button next to selector.
* [ ] make county optional on Step 0

**Comment by katherinepdavis** [comment]
This isn't appearing for me yet.
