### ISSUE TITLE
Lead user from VR confirmation into AB request

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#131]
Add link / button to vr step 8.

**Comment by karpet** [comment]
https://github.com/BlueprintKansas/ksvotes.org/pull/148

**Comment by karpet** [comment]
what county did you pick? I don't get an error. I get:

![screen shot 2018-08-09 at 3 51 48 pm](https://user-images.githubusercontent.com/99722/43925178-2feaa596-9bec-11e8-83a7-b806c961915a.png)

**Comment by katherinepdavis** [comment]
I’ve done at least Sedgwick and Test and never gotten a thank you page,
always a 500 error.

-kd
