### ISSUE TITLE
Fix/reformat VR 8 text

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#132]

**Comment by karpet** [comment]
Agreed. I suggest breaking it up into separate locale strings with a `_part_N` suffix. Then we can lay it out on the page.

We can also probably trim it down a bit with some wordsmithing.

If you add a comment here with the text broken up like you want it, I can reformat the relevant files.

**Comment by katherinepdavis** [comment]
changed in text doc

**Comment by karpet** [comment]
![screen shot 2018-08-09 at 4 55 21 pm](https://user-images.githubusercontent.com/99722/43928017-08b6c672-9bf5-11e8-8ebd-36301d443c57.png)
