### ISSUE TITLE
Add link to VV in match step so people can see sample ballot

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#135]

**Comment by karpet** [comment]
We can grab PDF link from the ksmyvoteinfo-py response

**Comment by karpet** [comment]
ksmyvoteinfo 0.5 has sample_ballot links

**Comment by karpet** [comment]
https://github.com/BlueprintKansas/ksvotes.org/pull/148

**Comment by katherinepdavis** [comment]
Johnson and Douglas don't have sample ballots in VV, so we should figure out how to deal with that.
