### ISSUE TITLE
Lower threshold on CAPTCHA

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#136]

**Comment by karpet** [comment]
Not sure what this means? Is it keeping you out occasionally?

**Comment by katherinepdavis** [comment]
Brian and I both got "click all the pictures where..." tasks when running through. He thinks there's a way to lower the threshold so that that happens less often.

I found this:

> As you stated you can lower the Security Level in the admin settings and this will lower the threshold that Google requires to verify a user as human, but if this is still not met a challenge will be presented.

https://stackoverflow.com/questions/42017068/can-i-make-google-recaptcha-2-0-only-show-the-checkbox-every-time

**Comment by karpet** [comment]
I have reset the stage keys to an account I can control and moved the admin to easiest setting.

please give it a try and let me know if that makes the difference you expected.

**Comment by katherinepdavis** [comment]
Brian still thinks the captcha is appearing too often.

**Comment by karpet** [comment]
unfortunately, the recaptcha admin has 3 settings (low medium high). It defaulted to medium. I already switched it to low. The only lower setting is to turn it off completely.

FWIW I have never gotten a prompt to enter image info.
