### ISSUE TITLE
after final step, should we allow "Back" or re-submission of form?

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#142]
Should we try and preview voters from returning to the affirmation page and re-posting? That would prevent multiple emails.

OTOH, what if they were legitimately trying to send a corrected form?

TBD

**Comment by katherinepdavis** [comment]
I think if the form is wrong they should go through the process again. I believe this is a very low use case at the moment -- I can remember one call from a guy frantic bc he is a MO resident and accidentally submitted, but only a handful of people who have submitted more than one form, and all of them were with some time in between (like months).

**Comment by karpet** [comment]
Ok. I added a "I'm all Done" button to the last page to prompt a click that will forget their session and effectively erase their PII from the browser. Think of it like a "log out" link. That and the 10 minute idle session timeout feature should address the security issues.
