### ISSUE TITLE
Language around signatures matching

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#151]
Especially for AB app signature

**Comment by karpet** [comment]
a JS confirm modal that users must ack

**Comment by katherinepdavis** [comment]
added to doc under 6AB_sign_modal

Is it easier for me to put directly in the JSON?

**Comment by karpet** [comment]
![screen shot 2018-08-14 at 3 22 55 pm](https://user-images.githubusercontent.com/99722/44116565-8018a962-9fd6-11e8-9724-86be0f3dc5de.png)
