### ISSUE TITLE
AB: Step counter skips from Step 1 to Step 3

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#154]
Use visual (dots?) instead of just words.

**Comment by karpet** [comment]
![screen shot 2018-08-09 at 7 35 27 am](https://user-images.githubusercontent.com/99722/43899224-d8b77a28-9ba6-11e8-9c57-b77522f022fa.png)

WIP first pass. styles TBD.

**Comment by karpet** [comment]
@katherinepdavis this nav change should be in stage shortly. Let me know what you think of the step styling.
