### ISSUE TITLE
AB1 - does election selection have to be type-in rather than drop-down? Brings up keyboard on mobile.

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#155]
feature flag based on current date vis-a-vis primary. don't show at all if between primary and general.

**Comment by karpet** [comment]
![screen shot 2018-08-09 at 3 55 00 pm](https://user-images.githubusercontent.com/99722/43925343-9bf4451c-9bec-11e8-88a1-a1ed1cc96433.png)
