### ISSUE TITLE
Comment character must be in first column in .env file

### ISSUE THREAD

**Issue by bartonstanley** [BlueprintKansas/ksvotes.org#159]
When following the instructions in README.md the `python manage.py db init` step failed, see traceback below. Removed the comment  following `SESSION_TTL=10` and after that the `python manage.py db init` step succeeded.

Suggest amending README.md so that the comment is either removed from the line with `SESSION_TTL=10` or so that the comment is above that line with the comment character in the first column.

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    app = create_app(os.getenv('APP_CONFIG') or 'default')
  File "/Users/bartonstanley/Sandbox/ksvotes.org/app/__init__.py", line 31, in create_app
    app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=int(app.config['SESSION_TTL']))
ValueError: invalid literal for int() with base 10: '10  # number of minutes before idle session expires'

**Comment by karpet** [comment]
Thanks @bartonstanley -- I've got a patch in #168 that should address this. Please give it a look and let me know if you think it clarifies enough.
