### ISSUE TITLE
additional text at top of step 7

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#173]
help UX with review county, review form, click ack and submit.

**Comment by katherinepdavis** [comment]
added to KSVotes Text doc. Writing it, I think it makes more sense to have the completed form, then the county clerk info, then the affirmation (right now we have clerk, form, affirmation). Or split it onto multiple pages -- form first, then next page has county clerk info and affirmation. I know we've discussed this before, I'm not sure what feels right.

**Comment by karpet** [comment]
![screen shot 2018-08-09 at 3 43 32 pm](https://user-images.githubusercontent.com/99722/43924752-05f0f926-9beb-11e8-8edf-af2db2b91afc.png)
