### ISSUE TITLE
Age help

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#209]
Currently:
> If you will be under 18 on election day (in November), leave this box blank. You will not be allowed to vote in November, but your registration will be processed and held until your 18th birthday.

Should it be tied to November? Does the same help apply to primary elections? Instead:

> If you will be under 18 on election day, select 'No'. You will not be allowed to vote, but your registration will be processed and held until your 18th birthday.

**Comment by katherinepdavis** [comment]
Still better to leave blank rather than selecting No. Is that possible? Other than that the language update is good.
