### ISSUE TITLE
DB schema

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#21]
Develop DB schema + models.

Related to #3  and #4

**Comment by karpet** [comment]
For `RegistrantModel`:

Naming question: the file is named `registrants`, but the class is named `RegistrantModel`. I would expect the file and class to be named the same, and I wouldn't expect "Model" in the class name. Is that a cultural convention for Python/Flask?

I would expect the class and file to be named "Registrant" (singular case, lowercase for the filename).

If you define `registration` as JSON but it is encrypted, will psql balk?
https://github.com/BlueprintKansas/ksvotes.org/blob/master/app/models/registrants.py#L17
I would expect it to be a `String` from the db's point of view.

How about `completed_at` as a `DateTime` instead of `completed_registration` as a `Boolean`? That way we get 2 values for the price of one: yes, they are complete, and when.

Any reason `party`, `is_citizen` and `is_eighteen` are called out as separate columns instead of part of the `registration` payload?

Why do we have a `race_ethnic` column? Is that part of the form that I don't remember?

Naming nit: let's be consistent with `DateTime` columns. Instead of `date_signed` maybe `signed_at`? That would match `created_at` and `completed_at`. Do we even need to track signed-vs-completed?

`ClerksModel` and `clerks` -- same question for naming. Column names look fine, though maybe a `created_at` and `updated_at` column so we can easily see the last time something was edited?

**Comment by JoshuaMitchell** [comment]
> For RegistrantModel:
> 
> Naming question: the file is named registrants, but the class is named RegistrantModel. I would expect the file and class to be named the same, and I wouldn't expect "Model" in the class name. Is that a cultural convention for Python/Flask?

It is not a convention... it is naming convention lag from working with GraphQl where I needed to separate out models and connections. I've updated.

> I would expect the class and file to be named "Registrant" (singular case, lowercase for the filename).
Updated.  Again leftover.  I've kept Registrant (the model name) in Camelcase for ORM integration down the road.


> If you define registration as JSON but it is encrypted, will psql balk?
> https://github.com/BlueprintKansas/ksvotes.org/blob/master/app/models/registrants.py#L17
> I would expect it to be a String from the db's point of view.
I don't know technically, but I assume you are 100% correct.  I've updated to string will do string parsing on a function level.

> How about completed_at as a DateTime instead of completed_registration as a Boolean? That way we get 2 values for the price of one: yes, they are complete, and when.
Good call. Done.

> Any reason party, is_citizen and is_eighteen are called out as separate columns instead of part of the registration payload?
Yes.  I thought it might be helpful to keep any non pii info out of the encrypted payload for general trends.  i.e.  Kate wants to write an sql query that surfaces the counts of folks by party that have completed/not completed registration.  Same for age... quick counts on aged registrations.  We can move this into the encrypted payload, but I didn't think it would be considered pii.

> Why do we have a race_ethnic column? Is that part of the form that I don't remember?
I pulled these columns from Jake's first draft of the DB.   We can pull this out if its not necessary?


> Naming nit: let's be consistent with DateTime columns. Instead of date_signed maybe signed_at? That would match created_at and completed_at. Do we even need to track signed-vs-completed?
Done

> ClerksModel and clerks -- same question for naming. Column names look fine, though maybe a created_at and updated_at column so we can easily see the last time something was edited?
Updated to convention

**Comment by karpet** [comment]
@JoshuaMitchell thanks for the quick updates.

For `race_ethnic` I don't think we want that. We *do* probably want to track which language the registration used. Maybe just change name to `lang`?

Do we want `completed_at` to have a default value?
```
completed_at = db.Column(db.Datetime, default=datetime.utcnow())
```
seems like we want it to default to `null`.

For `party` and the `is_*` columns, yes, seems fine to keep them out of the encrypted `registration`, knowing we will have to include them in the payload to NVRIS.

**Comment by JoshuaMitchell** [comment]
> For race_ethnic I don't think we want that. We do probably want to track which language the registration used. Maybe just change name to lang?

Great point.  Done.

> Do we want completed_at to have a default value?

No we don't.  Default removed.

> For party and the is_* columns, yes, seems fine to keep them out of the encrypted registration, knowing we will have to include them in the payload to NVRIS.

Yep.  Payload to NVRIS will be curated to what is needed and posted.
