### ISSUE TITLE
Add Alert when no county selected on Affirmation page

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#213]
![screen shot 2018-08-11 at 3 54 24 pm](https://user-images.githubusercontent.com/99722/43995979-047e3f78-9d7f-11e8-8782-0f000b2c64de.png)

**Comment by karpet** [comment]
![screen shot 2018-08-12 at 4 36 45 pm](https://user-images.githubusercontent.com/99722/44007384-f47e1ed2-9e59-11e8-86a1-a759d873acf7.png)

**Comment by katherinepdavis** [comment]
We're not using the vlookup to suggest most likely county based on zip?

**Comment by katherinepdavis** [comment]
Sorry, I see that's the connected issue. Just tried on stage and didn't get a suggested county, just the alert to select one.
