### ISSUE TITLE
Email clean up

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#214]
Needs:

- [x] Subject line
- [x] replace `<firstname>` with actual first name
- [x] add Clerk contact information
- [ ] What site should we point at for checking status? VoterView?

**Comment by karpet** [comment]
The email body says:

> Your registration has been forwarded to your local elections official, and you should have received a copy of that email. If you haven't received the email, please check your spam folder.

which is a little non-sensical. If you can read it, you have received the email. It *is* the email.

Should we just delete that line?

Or replace with something like:

> This email is being to both you and your county election office. Your completed form is attached.

**Comment by karpet** [comment]
@katherinepdavis some questions for you

**Comment by katherinepdavis** [comment]
Current state -- and I think this is good -- is 2 emails. 1 to voter with the text there (including "you should have received an email"), and another to the county clerk that CCs the voter. So the county clerk email says "see attached for a voter registration form." Concern is that if county clerks get an email that has text directed to the voter they may not realize that they're supposed to process it.

Does that make sense? I probably need to get you the text we have for the county clerk email now.

**Comment by karpet** [comment]
Ok now that makes sense to me. Master has 2 emails now: one to clerk, one (receipt) to voter.
