### ISSUE TITLE
alert-info after session time-out should persist 30 seconds or until manually dismissed

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#222]
right now it disappears too quickly.

**Comment by karpet** [comment]
need some clarity on whether this is actually an issue.

**Comment by katherinepdavis** [comment]
I tested today and had to manually dismiss, as expected. I’ll make a note
to check with other devices but I think we can consider it closed.

**Comment by karpet** [comment]
revisit per #236 if that comes up
