### ISSUE TITLE
Signature box should be bigger on mobile in portrait

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#225]
And/or, should be as wide as possible at all times.

From Brian: "In a perfect world, it'd also offer a screen rotate option."

**Comment by karpet** [comment]
When I turn my iPhone to landscape, the signature box gets bigger. Is that not true on other mobile devices?

I could make it go flush to the left/right margins, but that might look a little odd in the layout.

**Comment by katherinepdavis** [comment]
Might even be a height thing. Compare v1 to v2, v1 seems bigger:

**Comment by karpet** [comment]
yes I see what you mean. I will increase height and see if that helps.

**Comment by karpet** [comment]
I have bumped the min height up to match v1. Let me know if that helps.

**Comment by katherinepdavis** [comment]
Still feels smaller than v1, in both height and width. I’d say it’s better to have as much real estate as possible and ok to sacrifice some of the aesthetics

**Comment by karpet** [comment]
I have switched the Javascript lib we use for signing. Please try stage to see that helps.
