### ISSUE TITLE
tweak "clean up" message

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#236]
to make sure it's not ambiguous that we still have some info for our purposes. Might be ok as is. Placing this here to think about it.

**Comment by karpet** [comment]
How about:
> We've secured your personal information to protect your privacy.

which is both true and perhaps more emotionally satisfying?

**Comment by katherinepdavis** [comment]
Works for me!

**Comment by karpet** [comment]
disabled message for now till we can settle on mutually agreeable language.

**Comment by frankwiles** [comment]
@katherinepdavis did we ever figure out the language for this one?

**Comment by katherinepdavis** [comment]
No, we just put it on hold for now.
