### ISSUE TITLE
use signed_at column and fix default time

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#271]

**Comment by katherinepdavis** [comment]
What does signed_at mean? If it means time signature was applied to form, I don't think it's working correctly (showing times for unsigned forms).

**Comment by karpet** [comment]
Prior to this fix it was being set to whatever time the server was restarted. I just ran this in produciton to fix those old dates, setting them to `null`.

```sql
update registrants set signed_at=null where signed_at < '2018-08-17 23:59:17.17002'
```
