### ISSUE TITLE
add a way to clear registrant information after successful reg check

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#273]
Maybe something on the "we found your information" page that says "That's all I needed, I'm done" so that when it goes back to the main page, their info isn't stored.

This came up on campus -- when canvassers checked someone's reg and it was good, they had to individually delete that person's info in each field.

**Comment by karpet** [comment]
Added the same button that appears on final submission page, to forget the current session.

**Comment by katherinepdavis** [comment]
Good on stage -- can this be added to production?

**Comment by karpet** [comment]
deployed!
