### ISSUE TITLE
make county selection type-able?

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#285]

**Comment by katherinepdavis** [comment]
On front page -- so tablet users don't have to scroll through the full list.

**Comment by karpet** [comment]
Do you mean, type-able like they start typing and it autocompletes?

Maybe instead we should put the ZIP code field on the home page and remove the county altogether? That way we can look it up, since the VV check does not need it.

**Comment by katherinepdavis** [comment]
I'm ok with either, but option #2 sounds better. I was surprised how many students didn't know their county, and even though it's optional, it creates a bump in the road.

**Comment by karpet** [comment]
#294
