### ISSUE TITLE
handling of address change across counties

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#287]
When applicants who enter their previous address county in the reg lookup tool, their email goes to their previous county clerk by default, requires manual change to have it sent to their new county clerk.

**Comment by karpet** [comment]
sounds like we should run the ZIP -> County lookup on the USPS result too and report any discrepancy  and/or automatically override whatever county they picked on the first page. They can always manually change County on affirmation page.

**Comment by katherinepdavis** [comment]
Agreed

**Comment by karpet** [comment]
#294
