### ISSUE TITLE
debug email sending

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#288]
NR error thrown: 	
/app.main.VR.VR7_affirmation:vr7_affirmation
botocore.exceptions:ClientError
An error occurred (InvalidParameterValue) when calling the SendRawEmail operation: Empty required header 'To'.	Aug 22, 11:02 AM

Application was intended for Jackson County, which does have an email in the csv and db.

**Comment by karpet** [comment]
I have added some code to better catch this earlier. Not a fix, but hopefully can help reveal why this situation is happening.

**Comment by karpet** [comment]
This was fixed by #316
