### ISSUE TITLE
drop apt/lot field in AB address

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#306]
It's not on the form as a separate field, so we should mirror form and just do one address line.

**Comment by karpet** [comment]
The dilemma is if they have just registered, we skip the AB address form altogether and re-use what they had for VR. In either case, if the apt/lot is entered it gets concatenated with the street address line. I think we need to leave it there or risk not sending information they think they have entered in the VR flow.

**Comment by katherinepdavis** [comment]
That makes sense. I think the issue is still there, which is really that if I enter Apt = 1 then what shows up on the form is 123 Main St 1 instead of having any kind of prefix or indication. Is there a graceful solution?
