### ISSUE TITLE
Add blank/none/unaffiliated option to perm AB request

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#314]
Seems to be forcing people into D or R.

**Comment by karpet** [comment]
Should be possible to leave it blank -- is that not working?

**Comment by katherinepdavis** [comment]
I can leave it on "Select..." instead of choosing one, so it's working, but not as clear as if there were a blank option in the dropdown.

**Comment by karpet** [comment]
ok I will change the "Select a party..." text to something like "(none)" or "Unaffiliated".
