### ISSUE TITLE
long city names overlap state on AB form

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#317]
![Letters overlap .png](https://images.zenhubusercontent.com/5afcb67e4b5806bc2bd37b79/c744b5e9-354d-4399-9db3-86beae647e48)

**Comment by karpet** [comment]
I think the solution here is to shrink the font size everywhere and hope for the best. We can't really wrap inside such a small box, and the State box is ridiculous given that it is a Kansas-specific form.

**Comment by katherinepdavis** [comment]
Would it help to right-justify "Kansas" and/or freeze it as "KS"?

**Comment by karpet** [comment]
see #367
