### ISSUE TITLE
bug in previous name

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#321]
If you put in a previous name, hit next, then go back, you can no longer edit the previous name. The box is checked but no fields underneath; if you toggle the box off and on it clears on the name that had been there.

**Comment by frankwiles** [comment]
@karpet so is this at `/vr/name` in the change registration process? 

Also I found it a bit confusing on this page that we have a 'Name' header but not a 'Previous Name' header below.  Honestly wasn't sure which would be my current vs previous name and I can't be the only one. 

![Screen Shot 2018-10-07 at 9.47.34 AM.png](https://images.zenhubusercontent.com/5b9bc472aef63a0ac7e7bb40/2b174ca8-5400-4cca-bcb1-4de171929ae1)
