### ISSUE TITLE
change text on "Register to Vote" button only if VoterView returns a match

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#333]
Should say "Change my registration" or something similar.

**Comment by katherinepdavis** [comment]
How complicated is this to fix?

**Comment by karpet** [comment]
not hard.

**Comment by karpet** [comment]
PR in #357

**Comment by katherinepdavis** [comment]
Not seeing this active in stage, is it waiting to be merged?

**Comment by karpet** [comment]
it was merged, but apparently not deployed. Not sure why. Just manually deployed master to staging and confirmed:

![screen shot 2018-09-24 at 11 00 42 am](https://user-images.githubusercontent.com/99722/45963619-268f2280-bfe9-11e8-9d96-57c3a2c93f79.png)
