### ISSUE TITLE
Add Project Shield coverage

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#34]
Kate has admin access

**Comment by karpet** [comment]
Requires DNS changes to point at the Google CDN.

**Comment by karpet** [comment]
I may have underestimated the benefits this could provide.

see https://support.google.com/projectshield/answer/6358113?hl=en

I will prioritize for part of the DNS switch of ksvotes.org to v2.

**Comment by karpet** [comment]
Looking at this again, I'm not sure the complexity is worth the benefits. We already have load balancing and maintenance-free SSL certs with Heroku. Using PS requires us maintaining our own certs. I think this is premature optimization.
