### ISSUE TITLE
Add "testing purposes only" message to stage version

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#351]
We've had a few applications sneak through that appear to be real, so someone who was given the testing link might be giving it to real users. Just in case, we should flag that it's not functional.

**Comment by sjwdg** [comment]
Best practice would be to disable the email address for the county and grayscale across the application that it's "not valid". 
County clerks do not all apparently understand that TEST in the subject line means the application is not real.
