### ISSUE TITLE
add a voter reg/AB app ticker to bottom of front page

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#358]
Total # of each form processed by KSVotes.org in real time

**Comment by katherinepdavis** [comment]
Also a standalone format

**Comment by frankwiles** [comment]
Ok this is live on staging and production, just in the footer for now as I wasn't sure how prominent you wanted it displayed: 

![Screen Shot 2020-05-25 at 4 32 33 PM](https://user-images.githubusercontent.com/144159/82844222-5c169e00-9ea5-11ea-93b6-fae36e9de5a3.png)

There is also a JSON API version you can hit here: https://ksvotes.org/api/total-processed/ to get the data directly for any reason.
