### ISSUE TITLE
make font on apps bold

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#376]
Suggested by a clerk -- make it easier to distinguish from the form text

**Comment by karpet** [comment]
I also was considering a color other than black. I think bold might defeat the process of shrinking the font size and may not distinguish enough.

Green? Blue? Red?

**Comment by karpet** [comment]
here's an example in blue

![screen shot 2018-10-05 at 1 35 58 pm](https://user-images.githubusercontent.com/99722/46553634-9d5ad400-c8a3-11e8-964a-ba9f9caf9df0.png)

**Comment by karpet** [comment]
I have deployed the blue color to stage for testing.
