### ISSUE TITLE
Develop Schema to hold county officials / delivery targets

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#4]
<a href="https://github.com/jakelowen"><img src="https://avatars0.githubusercontent.com/u/5368008?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jakelowen](https://github.com/jakelowen)**
_Thursday Feb 08, 2018 at 02:25 GMT_
_Originally opened as https://github.com/gpsimpact/open_voter_reg/issues/5_

----

**Comment by karpet** [comment]
related to #18 -- need persistent storage model for county contacts.

**Comment by JoshuaMitchell** [comment]
@karpet can we consider this closed from my push yesterday with the db models?

**Comment by karpet** [comment]
I will close this one and open another to reflect the ability to manage the clerk data.
