### ISSUE TITLE
Advanced Ballot application flow

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#40]
The [AV1 form](http://www.kssos.org/forms/elections/AV1.pdf) should be offered as a option to users, both after completing registration and after confirming registration (step0).

Define the flow and document on the wiki.

**Comment by karpet** [comment]
The [AV2 form](http://www.kssos.org/forms/elections/AV2.pdf) flow should be included.

**Comment by karpet** [comment]
@JoshuaMitchell @katherinepdavis I have updated the https://github.com/BlueprintKansas/ksvotes.org/wiki/v2-flow with an integrated Advanced Ballot and Voter Registration flow. Some steps are very similar but different enough that I have added, e.g., the `AB` or `VR` suffix to indicate.

I assume all steps are re-entrant (the user can click Back and Forward and change their info).

**Comment by JoshuaMitchell** [comment]
@karpet question on:

> On POST, the server will:
> - validate whether the user is already registered, using the ksmyvoteinfo-py package.
> - if the user is already registered, then the response is a redirect to step 1AB.
> - if the user is not already registered, then the response is a redirect to step 1VR.

We should give them the option to update their registration if they are already registered, no?  So maybe if already registered it gives them two buttons one for AB and one for update VR?

**Comment by karpet** [comment]
@JoshuaMitchell great point -- I've updated the wiki. I think the AB step page should include that language, because it's really a decision point with 3 potential branches.

**Comment by katherinepdavis** [comment]
KSVotes Text doc is now updated with VR/AB steps
