### ISSUE TITLE
Cut off footer of VR form in NVRIS

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#400]
It says "mail this to the address provided for your state" and people are thinking they aren't done.

**Comment by karpet** [comment]
https://ksvotes-v2.s3.amazonaws.com/FEDVRENNVRIS-v2.png

**Comment by karpet** [comment]
Spanish version: https://ksvotes-v2.s3.amazonaws.com/FEDVRENNVRIS_SP-v2.png

**Comment by karpet** [comment]
in production for week+
