### ISSUE TITLE
Consider using subdomains for print use?

### ISSUE THREAD

**Issue by dannynovo** [BlueprintKansas/ksvotes.org#435]
I don't know how feasible this is, but when we consider using the ref feature in print materials, adding the ref?ref=variable certainly seems like it would reduce the number of people who will type it in to a browser.

It would be great if we could use an alternate URL scheme, like your-org.ksvotes.org

In our case that would be one of

votv.ksvotes.org
v2v.ksvotes.org
votertovoter.ksvotes.org

We haven't decided which we would use, but any of those would look great on printed materials.

Not a high priority, we'll definitely use the ref feature in our online materials at this point, but probably not in print materials.

Thanks for making this resource available!

**Comment by katherinepdavis** [comment]
Hey Danny! We have looked at this. Right now, we have it set so you can use www.ksvotes.org/r/your-variable to make it a little bit easier. So, consider using that, and we can see if another naming scheme works.
