### ISSUE TITLE
Secure voter can't change addresses

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#445]
Kansas allows voters to be hidden from public records -- they're referred to as "secure voters" and don't show up in the voterfile or on VoterView. However, VoterView will look them up -- it will just return a "no information" message instead of their address.

Because of this, when a secure voter attempts to change their address in KSVotes, the program tries to force the VV address in the Address step, but it's blank. So it overwrites the "KS" in the State field and then won't let the user type anything in (because that field is locked).

Can we change the Address field to default to KS rather than pulling what was in VV? I believe it should always be KS anyway, without exception.

**Comment by karpet** [comment]
I can take a stab at this @katherinepdavis
