### ISSUE TITLE
Change SoS Name on AB form to Scott Schwab 

### ISSUE THREAD

**Issue by spetrovic450** [BlueprintKansas/ksvotes.org#482]
We need to change the SoS name on the AB form to Scott Schwab and/or just SoS. We had a county clerk reach out about this a while back saying that the current form we send out has Kris Kobach's name on it. You can find the updated AB request form in the pdf form below. 
[SoS AB Request Form .pdf](https://github.com/BlueprintKansas/ksvotes.org/files/4678351/SoS.AB.Request.Form.pdf)

**Comment by karpet** [comment]
This is a duplicate of #412 

Comment here: https://github.com/BlueprintKansas/ksvotes.org/issues/412#issuecomment-663613589

@spetrovic450 if you can confirm we have the correct form image, we can proceed.
