### ISSUE TITLE
Add reg_found column to non-PIII db

### ISSUE THREAD

**Issue by DavisHammet** [BlueprintKansas/ksvotes.org#490]
Make a column in the non-PII database for if the SoS VoterView (“ksmyvoteinfo”) check successfully returns a registration record. I’m assuming “reg_found” is a boolean field where “true” means they’re already registered and “false” means they don’t show up as having a record in voter view.

**Comment by karpet** [comment]
Similar to #414 

I think what we really need is to add a searchable column(s) of boolean flags for all redacted items in the encrypted payload column. That way once the PII is removed, it's easy to search on whether it was present or not in the first place.

**Comment by DavisHammet** [comment]
The reason we want this field is to be able to know when someone goes to register (with a ref code), but learns they're already registered and stops. It helps to measure the work canvassers are putting in.

**Comment by karpet** [comment]
The `reg_found` column is now present in production. It is set whenever a SOS registration is successfully found. Whether the user continues on with the process must be discovered through examining other column values (such as `addr_lookup_complete`).

Other columns include:

```
ab_identification_found |
identification_found    |
reg_found               |
```
