### ISSUE TITLE
Rewrite NVRIS in Python

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#496]
To ease maintenance of this crucial service, let's rewrite NVRIS in Python. That makes it use the same language as the web app, and can still deploy as a lambda (with the same layer).

The existing NVRIS code has at least [one lib dependency that is deprecated](https://github.com/request/request/issues/3143) and is not being actively maintained upstream.

**Comment by karpet** [comment]
Started in https://github.com/BlueprintKansas/form-filler-py

**Comment by frankwiles** [comment]
Works for me! I debated it at one point fighting the Node 12.x upgrade just on the JS bits.
