### ISSUE TITLE
Add immediate email to AB requesters w/ no DL #

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#503]
If ID on the AB app doesn't match DL format, send email after submission:

Subject: Action needed to complete your advance ballot application

Dear [firstname],

Thank you for using KSVotes.org to complete an application for an advance ballot. 

You did not enter a Kansas driver's license or nondriver's identification card number. If you do not have a current and valid Kansas driver's license number or Kansas nondriver's identification card number, you must provide a copy of one of the following forms of photo identification to your local elections official in order to receive a ballot:

- Driver's license issued by Kansas or another state
- Nondriver's ID card issued by Kansas or another state
- U.S. passport
- Concealed carry of handgun license issued by Kansas or another state
- Employee badge or ID document issued by a government office
- U.S. military ID
- Student ID card issued by an accredited Kansas postsecondary educational institution
- Public assistance ID card issued by a government office
- ID card issued by an Indian tribe

If you do not have any of these forms of ID, you can call 316-530-5321 for assistance in getting a free voter ID.

Please send a copy of one of the above forms of ID to your county elections office at your earliest convenience. Their contact information is below:

[county elections office info]

Thank you!
KSVotes.org

**Comment by karpet** [comment]
https://github.com/BlueprintKansas/ksvotes.org/pull/518

@katherinepdavis do we want the email sent if this is a permanent AB application? I assume not per #512

**Comment by karpet** [comment]
This is now merged. If we need to disable for permanent AB, we can do that when we implement #512

**Comment by katherinepdavis** [comment]
Yes, disable for those completing perm AB form.
