### ISSUE TITLE
skip photo ID page for permanent AB requests

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#512]
Not required by law. Could workaround with text changes but would prefer not to confuse:

From Kansas Secretary of State’s website:

Exemptions from photo ID requirements exist for: permanent advance voters (voters with illness or disabilities); military and overseas voters and their spouses and dependents; and voter with religious objections who sign a Declaration of Religious Objection (Form DRO (Español)). Voters age 65 or older may use an expired photo ID.

 From Office of the Kansas Secretary of State SAFE Act FAQs:

 18. Permanent advance voters are exempt from photo ID. Are sick and disabled voters exempt? No. Voters on the permanent advance list are exempt under KSA 25-2908(i)(1). 

KSA 25-2908(i)(1):

(i) The following persons are exempt from the photographic identification document requirements of this section:

(1) Persons with a permanent physical disability that makes it impossible for such persons to travel to a county or state office to obtain a qualifying form of identification and have qualified for permanent advance voting status under K.S.A. 25-1124, and amendments thereto;

**Comment by karpet** [comment]
@katherinepdavis does this mean you want to skip the step completely? or just skip the modal with instructions that comes up if the field is left blank?

**Comment by katherinepdavis** [comment]
I would say skip the step entirely. Even if they do complete it, there's nowhere to put the ID # on the perm form.

**Comment by karpet** [comment]
@katherinepdavis this is now on stage -- feel free to close this ticket once you've confirmed behavior.
