### ISSUE TITLE
Spanish language form

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#6]
<a href="https://github.com/katherinepdavis"><img src="https://avatars0.githubusercontent.com/u/30677505?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [katherinepdavis](https://github.com/katherinepdavis)**
_Thursday Feb 08, 2018 at 17:17 GMT_
_Originally opened as https://github.com/gpsimpact/open_voter_reg/issues/7_

----

**Comment by karpet** [comment]
<a href="https://github.com/jakelowen"><img src="https://avatars0.githubusercontent.com/u/5368008?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jakelowen](https://github.com/jakelowen)**
_Friday Feb 09, 2018 at 18:11 GMT_

----

Probably best accomplished with some react internationalization library.

**Comment by karpet** [comment]
Localization should be on the server side.

**Comment by katherinepdavis** [comment]
GDoc with text:

[https://docs.google.com/spreadsheets/d/1-ulGteZtiPX6bNEZDX40zZg5ySOflRvxEPYzCHjsz4Q/edit?usp=sharing](url)

**Comment by karpet** [comment]
Thanks @katherinepdavis -- I tweaked a couple of things but this looks good to start with. I would suggest we line up who is going to do the Spanish translation, but hold off doing it till we can see the English text in the v2 site. That way we avoid having to keep the language translations in sync if we must alter the English during review.

**Comment by katherinepdavis** [comment]
I have people on board to translate. Agreed -- we'll wait until we're closer to completion before sending over to them.
