### ISSUE TITLE
AB election or permanent selection

### ISSUE THREAD

**Issue by karpet** [BlueprintKansas/ksvotes.org#88]
I don't see a place on the AB application to designate which election or applying for permanent status. Did that change or am I not remembering correctly? Our wiki flow refers to permanent and election selection.

**Comment by katherinepdavis** [comment]
For the SOS, it's two different forms: AV1 is regular application, AV2 is permanent application. Both have Political Party -- on AV1 it's just below Residential Address, very small.

**Comment by karpet** [comment]
Ah so permanent form is http://www.kssos.org/forms/elections/AV2.pdf

And "which election" only matters in that it is primary-vs-general so we know to check the political party box or not?

**Comment by katherinepdavis** [comment]
For the AV1 normal form, they have to specify which election they want the ballot for, since it only works for one. So it has to say the date for the designated election.

**Comment by karpet** [comment]
I can't find a Spanish version of AV2, nor do I see AV2 linked anywhere on http://www.sos.ks.gov/elections/elections_registration_voting.html

**Comment by katherinepdavis** [comment]
It's here: https://www.kssos.org/forms/Elections/AV2.pdf

I wouldn't be surprised if there isn't a Spanish version of that available, or at least not easily found.

**Comment by karpet** [comment]
To summarize:
It's the *date* of the election that must be filled in on the form, so we'll need a map of election name -> date for the voter to pick from.
In addition, if it's a primary election, the political party must be checked on the form.

**Comment by katherinepdavis** [comment]
All true for AV1. For AV2, election date is not needed and all applications must include the political party.
